### ISSUE TITLE
To upgrade crux-core to 1.15 or higher, begin-tx will now require a nil fork-at parameter

### ISSUE THREAD

**Issue by refset** [juxt/crux-corda#2]
(Just a heads-up to whoever starts looking at this module next)

https://github.com/juxt/crux-corda/blob/54e8c6b589d81c7c564b50a54d1c806de80e6308/crux-corda/src/main/clojure/crux/corda.clj#L135

Due to  https://github.com/juxt/crux/pull/1334

**Comment by remyrd** [comment]
Additionally,

Node and module configuration go through a breaking change past `1.15.0`. 

https://github.com/juxt/crux-corda/blob/54e8c6b589d81c7c564b50a54d1c806de80e6308/crux-corda/src/main/kotlin/crux/corda/CruxCorda.kt

`NodeConfigurator` and `ModuleConfigurator` should be replaced by `NodeConfiguration.Builder` and `ModuleConfiguration.Builder`

see https://github.com/juxt/crux/releases/tag/21.02-1.15.0 under breaking changes
