### ISSUE TITLE
Provide a function to obtain `StateAndRef` objects starting from a Crux query

### ISSUE THREAD

**Issue by remyrd** [juxt/crux-corda#3]
In order to fetch a `StateAndRef` object to use as input for a new transaction, one must use Corda's `net.corda.core.node.services.VaultService`. Ideally, `crux-corda` would provide a function to obtain this object, so that the user can use `CruxService`'s queries only.

Currently, this is the recommended way to obtain StateAndRef objects that have not yet been consumed - i.e. their latest version

```kotlin
serviceHub.vaultService.queryBy<IOUState>(QueryCriteria.VaultQueryCriteria(Vault.StateStatus.UNCONSUMED))
  .states.filter {
    // optionally filter states based on some criteria
}
```
Instead we would like to use particular outputs of a Crux query (such as the `cruxId`) to obtain `StateAndRef` objects.

A wrapper around this function call that filters States by `cruxId` is the simplest approach, though there's an open question about whether temporality should be factored in too.

**Comment by jarohen** [comment]
Maybe the easiest way to achieve this is for a user to use the Corda state's linearId as its `:crux.db/id` (hopefully a good choice of id anyway), at which point I assume it's a relatively straightforward lookup, rather than a query?
